# Generated by Django 3.2.20 on 2023-07-11 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('JP', 'Japan'), ('CN', 'China'), ('KR', 'South Korea'), ('AU', 'Australia')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('profile_image', models.ImageField(default='../default_profile_qlt6oa.png', upload_to='images/')),
                ('profile_banner', models.ImageField(default='../default-banner_jzvnux', upload_to='images/')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
