# Generated by Django 3.2.20 on 2023-10-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='build',
            name='ratings_count',
        ),
    ]
