# Generated by Django 3.2.20 on 2023-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20230713_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_case',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_cpu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_disk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_gpu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_mobo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_monitor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='build',
            name='build_ram',
            field=models.CharField(max_length=255),
        ),
    ]
