# Generated by Django 3.2.20 on 2023-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_user_rating_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='build',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
