# Generated by Django 3.2.20 on 2023-10-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_auto_20230924_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
