# Generated by Django 3.2.20 on 2023-10-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_build_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='gallery_image_1',
            field=models.ImageField(default='../default002_r4me0b', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='build',
            name='gallery_image_2',
            field=models.ImageField(default='../default001_p368vd', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='build',
            name='gallery_image_3',
            field=models.ImageField(default='../default003_zdfw1y', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='build',
            name='gallery_image_4',
            field=models.ImageField(default='../default005_p3syzs', upload_to='images/'),
        ),
    ]
