# Generated by Django 3.2.20 on 2023-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbuilder',
            name='content',
            field=models.TextField(default='Some information about the builder'),
        ),
    ]
