# Generated by Django 3.2.20 on 2023-07-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='owner',
            new_name='creator',
        ),
    ]
