# Generated by Django 3.2.20 on 2023-09-23 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_owner_comments_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating_1',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
