# Generated by Django 3.2.20 on 2023-09-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_rating_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rating_1',
        ),
    ]
