# Generated by Django 3.2.20 on 2023-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ['-rating_value']},
        ),
    ]
