# Generated by Django 3.2.20 on 2023-10-03 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0005_auto_20230924_1104'),
        ('comments', '0006_alter_ratings_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='user',
            new_name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('creator', 'build')},
        ),
    ]
