# Generated by Django 3.2.20 on 2023-07-15 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
