# Generated by Django 3.2.20 on 2023-07-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20230713_1911'),
        ('ratings', '0002_auto_20230715_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='builds.build'),
        ),
    ]
